spring:
  data:
    mongodb:
 #     authentication-database:
      #username: ${MONGO_USERNAME}
      #password: ${MONGO_PASSWORD}
      database: categoryDB
      port: 27017
      host: localhost
  application:
    name: category-service
server:
  port: 8080
