# Dockerfile has been added in all micro-services, you need to dockerize all micro-services and add docker-compose.yml file

version: '3'
services:
  mysql:
   container_name: mysql
   volumes:
    - ./dbData:/usr/lib/mysql_user
   image: mysql:5.6
   environment:
    MYSQL_DATABASE: keepnote 
    MYSQL_ROOT_PASSWORD: root
    MYSQL_USER: root
    MYSQL_PASSWORD: root
    #MYSQL_ROOT_HOST: '%'
   expose:
    - "3306"
   ports:
    - "3306:3306"
   network_mode: host
   restart: always

  mongodb:
   container_name: mongo
   image: mongo:3.7.9
   expose:
    - "27017"
   ports:
    - "27017:27017"
   command: mongod --smallfiles --logpath=/dev/null # --quiet
   network_mode: host
   environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
    #MONGO_INITDB_ROOT_USERNAME: root
    #MONGO_INITDB_ROOT_PASSWORD: root
   restart: always

  category-service:
   build:
     context: ./CategoryService
   restart: always
   network_mode: host
   depends_on:
     - mongodb
   ports:
     - 8080:8080

  note-service:
   build:
     context: ./NoteService
   restart: always
   network_mode: host
   depends_on:   
    - mongodb
   ports:
     - 8081:8081

  reminder-service:
   build:
     context: ./ReminderService
   restart: always
   network_mode: host
   depends_on:   
    - mongodb
   ports:
     - 8082:8082

  userauthentication-service:
   build:
     context: ./UserAuthentication-Service
   restart: always
   network_mode: host
   depends_on:
    - mysql
   ports:
     - 8083:8083
 
  user-service:
   build:
     context: ./UserService
   restart: always
   network_mode: host
   depends_on:   
    - mongodb
   ports:
     - 8084:8084