spring:
  data:
    mongodb:
      #username: ${MONGO_USERNAME}
      #password: ${MONGO_PASSWORD}
      database: noteDB
      port: 27017
      host: localhost
  application:
    name: note-service
server:
  port: 8081
